import json
import random
import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from db.redis_client import get_redis_sync

# ─── 60 unique products  (10 per category, zero overlap) ─────────────────────
PRODUCTS_DATA = [

    # ── Electronics ────────────────────────────────────────────────────────────
    {
        "name": "Apex ANC Headphones",
        "category": "Electronics",
        "price": 24900,
        "description": "Wireless over-ear headphones with 40-hour ANC and Hi-Res Audio certification.",
        "rating": 4.8,
        "brand": "Sony",
        "color": "black", "material": "plastic", "style": "wireless",
        "tags": "headphones,anc,wireless,audio,music",
        "image": "/images/noise_cancelling_buds.png",
    },
    {
        "name": "HorizonView 4K Monitor",
        "category": "Electronics",
        "price": 52000,
        "description": "27-inch 4K IPS display with 1ms response time and factory-calibrated colour accuracy.",
        "rating": 4.7,
        "brand": "Samsung",
        "color": "black", "material": "plastic", "style": "professional",
        "tags": "monitor,display,4k,computer,work",
        "image": "/images/ultra_wide_webcam.png",
    },
    {
        "name": "NovaSmart Smartwatch",
        "category": "Electronics",
        "price": 19500,
        "description": "Sleek AMOLED smartwatch with health tracking, ECG, and 7-day battery life.",
        "rating": 4.6,
        "brand": "Apple",
        "color": "silver", "material": "aluminium", "style": "premium",
        "tags": "watch,smartwatch,health,fitness,wearable",
        "image": "/images/mechanical_watch.png",
    },
    {
        "name": "PixelBuds Pro Wireless Earbuds",
        "category": "Electronics",
        "price": 12800,
        "description": "True-wireless earbuds with adaptive transparency mode and custom equaliser app.",
        "rating": 4.5,
        "brand": "Sony",
        "color": "white", "material": "plastic", "style": "wireless",
        "tags": "earbuds,wireless,bluetooth,audio,anc",
        "image": "/images/stream_buds.png",
    },
    {
        "name": "StreamCast 4K Webcam",
        "category": "Electronics",
        "price": 11200,
        "description": "4K/30fps ultra-wide webcam with AI auto-framing perfect for remote work and streaming.",
        "rating": 4.4,
        "brand": "Logitech",
        "color": "black", "material": "plastic", "style": "professional",
        "tags": "webcam,camera,4k,streaming,conference",
        "image": "/images/ultra_wide_webcam.png",
    },
    {
        "name": "CreatorBook Pro Laptop",
        "category": "Electronics",
        "price": 145000,
        "description": "15-inch OLED creator laptop with Intel Core Ultra 9 and 64 GB RAM for demanding workflows.",
        "rating": 4.9,
        "brand": "Samsung",
        "color": "grey", "material": "aluminium", "style": "professional",
        "tags": "laptop,creator,editing,display,computer",
        "image": "/images/creator_laptop.png",
    },
    {
        "name": "AuraGlow LED Desk Lamp",
        "category": "Electronics",
        "price": 4200,
        "description": "Touch-dimming LED lamp with circadian rhythm modes and wireless phone charging base.",
        "rating": 4.3,
        "brand": "IKEA",
        "color": "white", "material": "aluminium", "style": "minimalist",
        "tags": "lamp,light,desk,led,wireless-charging",
        "image": "/images/led_desk_lamp.png",
    },
    {
        "name": "BassWave Bluetooth Speaker",
        "category": "Electronics",
        "price": 8900,
        "description": "360° waterproof portable speaker with 24-hour playtime and deep bass radiator.",
        "rating": 4.6,
        "brand": "Sony",
        "color": "navy", "material": "fabric", "style": "portable",
        "tags": "speaker,bluetooth,portable,audio,waterproof",
        "image": "/images/bluetooth_speaker.png",
    },
    {
        "name": "PowerVault 25K Charger",
        "category": "Electronics",
        "price": 5600,
        "description": "65 W GaN power bank with PD 3.0, 25 000 mAh capacity and dual USB-C ports.",
        "rating": 4.5,
        "brand": "Logitech",
        "color": "black", "material": "plastic", "style": "compact",
        "tags": "charger,powerbank,battery,usbc,travel",
        "image": "/images/portable_charger_20k.png",
    },
    {
        "name": "SurfacePad 2-in-1 Tablet",
        "category": "Electronics",
        "price": 98000,
        "description": "Versatile 13-inch 2-in-1 with pen support, detachable keyboard and all-day battery.",
        "rating": 4.7,
        "brand": "Apple",
        "color": "silver", "material": "aluminium", "style": "professional",
        "tags": "tablet,laptop,2-in-1,work,windows",
        "image": "/images/surface_pro.png",
    },

    # ── Apparel ────────────────────────────────────────────────────────────────
    {
        "name": "UrbanEdge Leather Backpack",
        "category": "Apparel",
        "price": 8500,
        "description": "Full-grain leather 22L backpack with padded laptop sleeve and antique brass fittings.",
        "rating": 4.8,
        "brand": "Nike",
        "color": "tan", "material": "leather", "style": "casual",
        "tags": "backpack,bag,leather,travel,laptop",
        "image": "/images/leather_backpack.png",
    },
    {
        "name": "CloudWeave Organic Cotton Tee",
        "category": "Apparel",
        "price": 1800,
        "description": "GOTS-certified organic cotton crew-neck with a relaxed unisex silhouette.",
        "rating": 4.5,
        "brand": "Nike",
        "color": "white", "material": "cotton", "style": "minimalist",
        "tags": "tshirt,tee,organic,unisex,casual",
        "image": "/images/silk_pillowcase_set.png",
    },
    {
        "name": "ArcticShield Waterproof Parka",
        "category": "Apparel",
        "price": 14500,
        "description": "Gore-Tex waterproof parka rated to -20 °C with sealed seams and adjustable hood.",
        "rating": 4.7,
        "brand": "Nike",
        "color": "olive", "material": "nylon", "style": "outdoor",
        "tags": "parka,jacket,waterproof,winter,outdoor",
        "image": "/images/leather_backpack.png",
    },
    {
        "name": "VelvetLux Silk Pillowcase Set",
        "category": "Apparel",
        "price": 3200,
        "description": "22 momme mulberry silk pillowcase set that reduces hair friction and retains skin moisture.",
        "rating": 4.6,
        "brand": "IKEA",
        "color": "cream", "material": "silk", "style": "luxury",
        "tags": "pillowcase,silk,bedding,sleep,soft",
        "image": "/images/silk_pillowcase_set.png",
    },
    {
        "name": "StepUp Classic Sneakers",
        "category": "Apparel",
        "price": 6800,
        "description": "Low-top canvas sneakers with memory foam insole and vulcanised rubber outsole.",
        "rating": 4.4,
        "brand": "Nike",
        "color": "white", "material": "canvas", "style": "casual",
        "tags": "shoes,sneakers,casual,canvas,footwear",
        "image": "/images/leather_backpack.png",
    },
    {
        "name": "Indigo Heritage Denim Jacket",
        "category": "Apparel",
        "price": 5900,
        "description": "Stone-washed selvedge denim trucker jacket with contrast stitching and brass buttons.",
        "rating": 4.6,
        "brand": "Nike",
        "color": "blue", "material": "cotton", "style": "vintage",
        "tags": "jacket,denim,vintage,fashion,casual",
        "image": "/images/leather_backpack.png",
    },
    {
        "name": "ThermaKnit Merino Beanie",
        "category": "Apparel",
        "price": 1600,
        "description": "100% merino wool ribbed beanie with natural temperature regulation and odour resistance.",
        "rating": 4.5,
        "brand": "Nike",
        "color": "charcoal", "material": "wool", "style": "casual",
        "tags": "beanie,wool,winter,hat,accessories",
        "image": "/images/silk_pillowcase_set.png",
    },
    {
        "name": "PolarPro Fleece Hoodie",
        "category": "Apparel",
        "price": 4200,
        "description": "Recycled polyester midlayer fleece with kangaroo pocket and half-zip collar.",
        "rating": 4.4,
        "brand": "Nike",
        "color": "grey", "material": "fabric", "style": "outdoor",
        "tags": "hoodie,fleece,jacket,midlayer,outdoor",
        "image": "/images/leather_backpack.png",
    },
    {
        "name": "LunaShade Polarised Sunglasses",
        "category": "Apparel",
        "price": 3400,
        "description": "UV400-polarised acetate-frame sunglasses with spring-hinge temples for all-day comfort.",
        "rating": 4.3,
        "brand": "Nike",
        "color": "black", "material": "acetate", "style": "modern",
        "tags": "sunglasses,eyewear,polarised,uv400,summer",
        "image": "/images/silk_pillowcase_set.png",
    },
    {
        "name": "CasaLux Cashmere Scarf",
        "category": "Apparel",
        "price": 5200,
        "description": "Grade-A Mongolian cashmere scarf woven in a reversible double-faced pattern.",
        "rating": 4.7,
        "brand": "Nike",
        "color": "beige", "material": "cashmere", "style": "premium",
        "tags": "scarf,cashmere,winter,luxury,accessories",
        "image": "/images/silk_pillowcase_set.png",
    },

    # ── Home ───────────────────────────────────────────────────────────────────
    {
        "name": "Artisan Oak Standing Desk",
        "category": "Home",
        "price": 42000,
        "description": "Motorised height-adjustable standing desk with solid oak top and programmable presets.",
        "rating": 4.8,
        "brand": "IKEA",
        "color": "brown", "material": "wood", "style": "ergonomic",
        "tags": "desk,standing,motorised,office,adjustable",
        "image": "/images/standing_desk.png",
    },
    {
        "name": "BaristaCraft Espresso Maker",
        "category": "Home",
        "price": 18500,
        "description": "15-bar pump espresso machine with PID temperature control and 58mm portafilter.",
        "rating": 4.7,
        "brand": "Samsung",
        "color": "black", "material": "steel", "style": "premium",
        "tags": "espresso,coffee,kitchen,barista,machine",
        "image": "/images/coffee_maker_deluxe.png",
    },
    {
        "name": "ZenDrop Ceramic Pour-Over Set",
        "category": "Home",
        "price": 3800,
        "description": "Hand-thrown ceramic dripper and carafe set designed for smooth,single-origin pour-over.",
        "rating": 4.6,
        "brand": "IKEA",
        "color": "white", "material": "ceramic", "style": "minimalist",
        "tags": "coffee,pour-over,kitchen,ceramic,handmade",
        "image": "/images/coffee_maker_deluxe.png",
    },
    {
        "name": "PrecisionPro Kitchen Scale",
        "category": "Home",
        "price": 2800,
        "description": "Tempered-glass digital kitchen scale accurate to 0.1 g with built-in timer and tare.",
        "rating": 4.5,
        "brand": "IKEA",
        "color": "silver", "material": "glass", "style": "minimalist",
        "tags": "scale,kitchen,cooking,baking,digital",
        "image": "/images/kitchen_scale_pro.png",
    },
    {
        "name": "HydroSense Smart Water Bottle",
        "category": "Home",
        "price": 3500,
        "description": "Insulated steel bottle with LED hydration reminder and companion app syncing.",
        "rating": 4.4,
        "brand": "IKEA",
        "color": "teal", "material": "steel", "style": "smart",
        "tags": "bottle,water,smart,hydration,led,tracker",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "Serenity Aromatherapy Diffuser",
        "category": "Home",
        "price": 4200,
        "description": "Ultrasonic oil diffuser with warm ambient light and 500 ml reservoir for large rooms.",
        "rating": 4.6,
        "brand": "IKEA",
        "color": "wood", "material": "wood", "style": "modern",
        "tags": "diffuser,aromatherapy,home,relax,oil",
        "image": "/images/artisan_desk.png",
    },
    {
        "name": "LodgePro Cast Iron Skillet",
        "category": "Home",
        "price": 4800,
        "description": "Pre-seasoned 12-inch cast iron skillet with heat-assist handle and even heat distribution.",
        "rating": 4.8,
        "brand": "IKEA",
        "color": "black", "material": "metal", "style": "vintage",
        "tags": "skillet,kitchen,cooking,cast-iron,pan",
        "image": "/images/kitchen_scale_pro.png",
    },
    {
        "name": "CloudRest Memory Foam Topper",
        "category": "Home",
        "price": 9800,
        "description": "3-inch open-cell memory foam mattress topper with cooling gel layer and washable cover.",
        "rating": 4.7,
        "brand": "IKEA",
        "color": "white", "material": "foam", "style": "premium",
        "tags": "mattress,topper,foam,sleep,bedding",
        "image": "/images/silk_pillowcase_set.png",
    },
    {
        "name": "Nordic Ceramic Vase Set",
        "category": "Home",
        "price": 2200,
        "description": "Set of three matte ceramic vases in graduated heights, ideal for dried florals.",
        "rating": 4.5,
        "brand": "IKEA",
        "color": "beige", "material": "ceramic", "style": "minimalist",
        "tags": "vase,decor,ceramic,home,nordic",
        "image": "/images/artisan_desk.png",
    },
    {
        "name": "EcoSlice Bamboo Cutting Board",
        "category": "Home",
        "price": 1900,
        "description": "Extra-large end-grain bamboo board with juice grooves, rubber feet and a side handle.",
        "rating": 4.4,
        "brand": "IKEA",
        "color": "brown", "material": "wood", "style": "casual",
        "tags": "cutting-board,kitchen,bamboo,eco,cooking",
        "image": "/images/kitchen_scale_pro.png",
    },

    # ── Sports ─────────────────────────────────────────────────────────────────
    {
        "name": "ZenFlow Premium Yoga Mat",
        "category": "Sports",
        "price": 5400,
        "description": "6 mm non-slip natural rubber yoga mat with alignment lines and carry strap.",
        "rating": 4.8,
        "brand": "Nike",
        "color": "green", "material": "rubber", "style": "fitness",
        "tags": "mat,yoga,pilates,fitness,exercise,non-slip",
        "image": "/images/yoga_mat_premium.png",
    },
    {
        "name": "IronCore Adjustable Dumbbell Set",
        "category": "Sports",
        "price": 12800,
        "description": "Adjustable 5–52.5 lb dumbbell pair with dial-selector mechanism and compact footprint.",
        "rating": 4.8,
        "brand": "Nike",
        "color": "black", "material": "metal", "style": "fitness",
        "tags": "dumbbells,weights,gym,strength,adjustable",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "FlexBand Pro Resistance Bands Kit",
        "category": "Sports",
        "price": 2800,
        "description": "Set of 5 latex-free loop bands (10–50 lb) with workout guide and carry bag.",
        "rating": 4.6,
        "brand": "Nike",
        "color": "orange", "material": "rubber", "style": "fitness",
        "tags": "bands,resistance,workout,gym,elastic",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "GlidePro Foam Roller Set",
        "category": "Sports",
        "price": 3200,
        "description": "Dual-density EVA foam roller set with flat and ridged surfaces for targeted myofascial release.",
        "rating": 4.5,
        "brand": "Nike",
        "color": "blue", "material": "foam", "style": "fitness",
        "tags": "roller,foam,massage,recovery,muscle",
        "image": "/images/foam_roller_set.png",
    },
    {
        "name": "Cyclone Smart Jump Rope",
        "category": "Sports",
        "price": 3800,
        "description": "Digital jump rope with auto-counting sensor, calorie tracker and adjustable cable length.",
        "rating": 4.4,
        "brand": "Nike",
        "color": "blue", "material": "plastic", "style": "smart",
        "tags": "rope,jump,cardio,fitness,smart",
        "image": "/images/foam_roller_set.png",
    },
    {
        "name": "ProCourt Tennis Racket",
        "category": "Sports",
        "price": 8900,
        "description": "Carbon-fibre 100 sq-in head racket strung at 55 lb for intermediate-to-advanced players.",
        "rating": 4.7,
        "brand": "Nike",
        "color": "white", "material": "carbon", "style": "professional",
        "tags": "tennis,racket,sports,carbon,court",
        "image": "/images/foam_roller_set.png",
    },
    {
        "name": "AeroPeak Cycling Helmet",
        "category": "Sports",
        "price": 7200,
        "description": "Aerodynamic MIPS-equipped road helmet with 24 vents and dial-fit retention system.",
        "rating": 4.6,
        "brand": "Nike",
        "color": "black", "material": "plastic", "style": "modern",
        "tags": "helmet,cycling,bike,mips,road",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "HydraFit Protein Shaker",
        "category": "Sports",
        "price": 1200,
        "description": "BPA-free 700 ml shaker with wire-whisk ball and leak-proof flip lid for pre/post workout.",
        "rating": 4.3,
        "brand": "Nike",
        "color": "black", "material": "plastic", "style": "casual",
        "tags": "shaker,protein,gym,workout,bottle",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "PowerBell Kettlebell 16 kg",
        "category": "Sports",
        "price": 5600,
        "description": "Competition-spec flat-bottomed powder-coated kettlebell with consistent centre-of-mass.",
        "rating": 4.7,
        "brand": "Nike",
        "color": "silver", "material": "metal", "style": "fitness",
        "tags": "kettlebell,weights,gym,strength,functional",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "SwiftDry Microfibre Gym Towel",
        "category": "Sports",
        "price": 900,
        "description": "Quick-drying antimicrobial microfibre towel (40×80 cm) with zip pocket and snap loop.",
        "rating": 4.2,
        "brand": "Nike",
        "color": "grey", "material": "fabric", "style": "minimalist",
        "tags": "towel,gym,microfibre,workout,sweat",
        "image": "/images/foam_roller_set.png",
    },

    # ── Beauty ─────────────────────────────────────────────────────────────────
    {
        "name": "LumaPlex Vitamin C Serum",
        "category": "Beauty",
        "price": 2800,
        "description": "15% L-ascorbic acid serum with ferulic acid and vitamin E to brighten and even skin tone.",
        "rating": 4.8,
        "brand": "Samsung",
        "color": "orange", "material": "glass", "style": "premium",
        "tags": "serum,vitamin-c,skincare,face,brightening",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "AquaBoost Hyaluronic Moisturiser",
        "category": "Beauty",
        "price": 2200,
        "description": "Fragrance-free moisturiser with multi-weight hyaluronic acid for 72-hour deep hydration.",
        "rating": 4.7,
        "brand": "Samsung",
        "color": "white", "material": "plastic", "style": "minimalist",
        "tags": "moisturiser,hyaluronic,skincare,hydration,face",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "JadeGlo Facial Roller",
        "category": "Beauty",
        "price": 1600,
        "description": "Authentic jade dual-ended face roller to reduce puffiness and improve product absorption.",
        "rating": 4.6,
        "brand": "Samsung",
        "color": "jade", "material": "jade", "style": "natural",
        "tags": "jade,roller,face,skincare,beauty-tool",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "NeutralEdge Makeup Brush Set",
        "category": "Beauty",
        "price": 3400,
        "description": "16-piece vegan bristle brush set with ergonomic stainless handles in a magnetic roll-up case.",
        "rating": 4.7,
        "brand": "Samsung",
        "color": "rose", "material": "wood", "style": "professional",
        "tags": "brushes,makeup,tools,vegan,face",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "VelvetMatte Liquid Lipstick",
        "category": "Beauty",
        "price": 1200,
        "description": "Transfer-proof liquid lipstick with vitamin E conditioning and full-opaque matte finish.",
        "rating": 4.5,
        "brand": "Samsung",
        "color": "red", "material": "plastic", "style": "glamor",
        "tags": "lipstick,matte,makeup,lips,colour",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "SolarGuard SPF 50 Sunscreen",
        "category": "Beauty",
        "price": 1800,
        "description": "Lightweight mineral sunscreen SPF 50+ with zinc oxide, no white cast, reef-safe formula.",
        "rating": 4.6,
        "brand": "Samsung",
        "color": "white", "material": "plastic", "style": "natural",
        "tags": "sunscreen,spf,skincare,mineral,uva,uvb",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "GlowPeel Enzyme Exfoliant",
        "category": "Beauty",
        "price": 2400,
        "description": "Papaya and pineapple enzyme exfoliant that gently resurfaces skin for a lit-from-within glow.",
        "rating": 4.5,
        "brand": "Samsung",
        "color": "peach", "material": "plastic", "style": "natural",
        "tags": "exfoliant,skincare,enzyme,face,glow",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "SilkRevive Argan Hair Oil",
        "category": "Beauty",
        "price": 2100,
        "description": "Pure Moroccan argan oil blend that tames frizz, adds shine and protects against heat up to 230 °C.",
        "rating": 4.6,
        "brand": "Samsung",
        "color": "gold", "material": "glass", "style": "premium",
        "tags": "hair-oil,argan,haircare,frizz,shine",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "PetalDew Rose Water Toner",
        "category": "Beauty",
        "price": 1400,
        "description": "Triple-distilled Bulgarian rose water toner that balances pH and primes skin for serums.",
        "rating": 4.4,
        "brand": "Samsung",
        "color": "pink", "material": "plastic", "style": "natural",
        "tags": "toner,rose-water,skincare,face,hydration",
        "image": "/images/smart_water_bottle.png",
    },
    {
        "name": "ChromaPop Eyeshadow Palette",
        "category": "Beauty",
        "price": 3200,
        "description": "18-shade highly-pigmented eyeshadow palette spanning matte, shimmer and duochrome finishes.",
        "rating": 4.8,
        "brand": "Samsung",
        "color": "multi", "material": "plastic", "style": "glamor",
        "tags": "palette,eyeshadow,makeup,eyes,pigment",
        "image": "/images/smart_water_bottle.png",
    },

    # ── Toys ───────────────────────────────────────────────────────────────────
    {
        "name": "SkyPulse FPV Drone",
        "category": "Toys",
        "price": 18500,
        "description": "Beginner-friendly 4K FPV drone with obstacle avoidance, 30-min flight time and geo-fencing.",
        "rating": 4.7,
        "brand": "Logitech",
        "color": "black", "material": "plastic", "style": "modern",
        "tags": "drone,fpv,4k,flying,rc",
        "image": "/images/foam_roller_set.png",
    },
    {
        "name": "MagnoBrick 250-Piece Set",
        "category": "Toys",
        "price": 4800,
        "description": "Magnetic building blocks in geometric shapes that help children aged 3+ develop spatial skills.",
        "rating": 4.8,
        "brand": "Logitech",
        "color": "multi", "material": "plastic", "style": "educational",
        "tags": "magnetic,blocks,building,kids,stem",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "TurboTerrain RC Monster Truck",
        "category": "Toys",
        "price": 5600,
        "description": "1/10 scale 4WD all-terrain RC truck with brushless motor and waterproof electronics.",
        "rating": 4.6,
        "brand": "Logitech",
        "color": "red", "material": "plastic", "style": "action",
        "tags": "rc,truck,monster,car,remote-control",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "MindPath Wooden Puzzle 500 pc",
        "category": "Toys",
        "price": 1800,
        "description": "FSC-certified premium wooden jigsaw with interlocking pieces and an illustrated world map theme.",
        "rating": 4.6,
        "brand": "Logitech",
        "color": "multi", "material": "wood", "style": "educational",
        "tags": "puzzle,jigsaw,kids,learning,wooden",
        "image": "/images/artisan_desk.png",
    },
    {
        "name": "CosmoHero Action Figure Set",
        "category": "Toys",
        "price": 3200,
        "description": "6-inch articulated hero action figure with 12 accessories and light-up chest armour feature.",
        "rating": 4.5,
        "brand": "Logitech",
        "color": "blue", "material": "plastic", "style": "action",
        "tags": "action-figure,hero,toy,kids,accessories",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "CuddleCloud Plush Panda",
        "category": "Toys",
        "price": 2200,
        "description": "Ultra-soft 45 cm stuffed panda made with hypoallergenic micro-plush and recycled fill.",
        "rating": 4.7,
        "brand": "Logitech",
        "color": "white", "material": "fabric", "style": "classic",
        "tags": "plush,panda,stuffed,soft,toy",
        "image": "/images/foam_roller_set.png",
    },
    {
        "name": "StrategyQuest Board Game",
        "category": "Toys",
        "price": 3800,
        "description": "Award-winning strategy board game for 2–6 players aged 10+ with 120-min play time.",
        "rating": 4.8,
        "brand": "Logitech",
        "color": "multi", "material": "cardboard", "style": "classic",
        "tags": "board-game,strategy,family,kids,adult",
        "image": "/images/artisan_desk.png",
    },
    {
        "name": "AquaBlast Super Soaker",
        "category": "Toys",
        "price": 1600,
        "description": "Pump-action water blaster with 1.5 L reservoir and precision nozzle for up to 10 m range.",
        "rating": 4.4,
        "brand": "Logitech",
        "color": "green", "material": "plastic", "style": "action",
        "tags": "water-gun,summer,outdoor,kids,play",
        "image": "/images/foam_roller_set.png",
    },
    {
        "name": "ClayStudio Modelling Kit",
        "category": "Toys",
        "price": 2400,
        "description": "28-colour air-dry modelling clay set with sculpting tools and printed project cards.",
        "rating": 4.5,
        "brand": "Logitech",
        "color": "multi", "material": "clay", "style": "educational",
        "tags": "clay,art,kids,modelling,creative",
        "image": "/images/resistance_bands_kit.png",
    },
    {
        "name": "GravityYo Responsive Yo-Yo",
        "category": "Toys",
        "price": 1400,
        "description": "Professional-grade aluminium yo-yo with unresponsive bearing system for learning string tricks.",
        "rating": 4.4,
        "brand": "Logitech",
        "color": "silver", "material": "metal", "style": "classic",
        "tags": "yoyo,trick,toy,skill,aluminium",
        "image": "/images/resistance_bands_kit.png",
    },
]


def generate_mock_products():
    client = get_redis_sync()

    # Clear previous data to avoid stale entries
    old_ids = client.smembers("products:all")
    for old_id in old_ids:
        client.delete(f"product:{old_id}")
    client.delete("products:all")

    for i, p_info in enumerate(PRODUCTS_DATA):
        prod_id    = f"prod-{i + 1}"
        base_price = p_info.get("price", round((15.00 + (i % 10) * 12.5 + random.random() * 30) * 82))

        product_data = {
            "id":            prod_id,
            "name":          p_info["name"],
            "category":      p_info["category"],
            "base_price":    base_price,
            "current_price": base_price,
            "rating":        p_info.get("rating", round(3.5 + random.random() * 1.5, 1)),
            "reviewCount":   int(50 + random.random() * 950),
            "demandVelocity": random.randint(20, 100),
            "brand":         p_info.get("brand", "Generic"),
            "description":   p_info.get("description", f"A high-quality {p_info['name'].lower()}."),
            "specs": json.dumps({
                "Weight":   f"{round(0.3 + random.random() * 2, 1)} kg",
                "Warranty": "2 years",
                "Origin":   "Imported",
                "Color":    p_info.get("color", "").capitalize(),
                "Material": p_info.get("material", "").capitalize(),
            }),
            "image":    p_info.get("image", "/images/yoga_mat_premium.png"),
            "color":    p_info.get("color", ""),
            "material": p_info.get("material", ""),
            "style":    p_info.get("style", ""),
            "tags":     p_info.get("tags", ""),
        }

        client.hset(f"product:{prod_id}", mapping=product_data)
        client.sadd("products:all", prod_id)

    counts = {}
    for p in PRODUCTS_DATA:
        counts[p["category"]] = counts.get(p["category"], 0) + 1
    print(f"Mock database seeded with {len(PRODUCTS_DATA)} products:")
    for cat, n in counts.items():
        print(f"  {cat}: {n}")


if __name__ == "__main__":
    generate_mock_products()
